
name: Generate 3D Contribution Profile

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate 3D Contribution Profile

    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D Contribution Profile
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Joes005

      - name: Commit generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Generate 3D contribution profile"
          git push
